### PR TITLE
New themes for Lyrics Page + fixing static themes

### PR DESCRIPTION
**Pull request by IshanJ25**
Fixed a couple of themes and added 21 new themes for the lyrics theme page. Some notable themes are "discord" and "github".

### CODE REVIEW

**Comment by IshanJ25** [comment]
here are the previews of the themes:

| Theme | Name|
|---------|-------|
Slide1 | default
Slide2 | red
Slide3 | orange
Slide4 | yellow
Slide5 | spotify
Slide6 | blue
Slide7 | purple
Slide8 | strawberry
Slide9 | pumpkin
Slide10 | sandbar
Slide11 | radium
Slide12 | oceano
Slide13 | royal
Slide14 | github
Slide15 | discord
Slide16 | drot
Slide17 | forest
Slide18 | fresh
Slide19 | zing
Slide20 | pinkle
Slide21 | krux
Slide22 | blueberry
Slide23 | postlight


Please merge this commit
Thanks

Edit: these are mockups i made in PowerPoint using handpicked colors. Song: [Senorita](https://open.spotify.com/track/0TK2YIli7K1leLovkQiNik?si=28c26a076e914dcd)

**Comment by amd64fox** [comment]
Lots of good themes, thank you

The only thing in the latest versions of the theme does not work 100 percent in SpotX, two parameters are not read `maxmatch` and `hover`, I need to finish this

I also noticed a double `##` in some of your colors, I think this is a typo

**Review by IshanJ25 — COMMENTED** [review]
fixed the double '##' thing

**Comment by amd64fox** [comment]
merged, thanks for your work

**Pull request merged**
